//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client2.ReverseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="localhost", ConfigurationName="ReverseService.ReviseServiceSoap")]
    public interface ReviseServiceSoap {
        
        // CODEGEN: Generating message contract since element name text from namespace localhost is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="localhost/ReverseText", ReplyAction="*")]
        Client2.ReverseService.ReverseTextResponse ReverseText(Client2.ReverseService.ReverseTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="localhost/ReverseText", ReplyAction="*")]
        System.Threading.Tasks.Task<Client2.ReverseService.ReverseTextResponse> ReverseTextAsync(Client2.ReverseService.ReverseTextRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseText", Namespace="localhost", Order=0)]
        public Client2.ReverseService.ReverseTextRequestBody Body;
        
        public ReverseTextRequest() {
        }
        
        public ReverseTextRequest(Client2.ReverseService.ReverseTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="localhost")]
    public partial class ReverseTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public ReverseTextRequestBody() {
        }
        
        public ReverseTextRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseTextResponse", Namespace="localhost", Order=0)]
        public Client2.ReverseService.ReverseTextResponseBody Body;
        
        public ReverseTextResponse() {
        }
        
        public ReverseTextResponse(Client2.ReverseService.ReverseTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="localhost")]
    public partial class ReverseTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReverseTextResult;
        
        public ReverseTextResponseBody() {
        }
        
        public ReverseTextResponseBody(string ReverseTextResult) {
            this.ReverseTextResult = ReverseTextResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReviseServiceSoapChannel : Client2.ReverseService.ReviseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReviseServiceSoapClient : System.ServiceModel.ClientBase<Client2.ReverseService.ReviseServiceSoap>, Client2.ReverseService.ReviseServiceSoap {
        
        public ReviseServiceSoapClient() {
        }
        
        public ReviseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReviseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReviseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client2.ReverseService.ReverseTextResponse Client2.ReverseService.ReviseServiceSoap.ReverseText(Client2.ReverseService.ReverseTextRequest request) {
            return base.Channel.ReverseText(request);
        }
        
        public string ReverseText(string text) {
            Client2.ReverseService.ReverseTextRequest inValue = new Client2.ReverseService.ReverseTextRequest();
            inValue.Body = new Client2.ReverseService.ReverseTextRequestBody();
            inValue.Body.text = text;
            Client2.ReverseService.ReverseTextResponse retVal = ((Client2.ReverseService.ReviseServiceSoap)(this)).ReverseText(inValue);
            return retVal.Body.ReverseTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client2.ReverseService.ReverseTextResponse> Client2.ReverseService.ReviseServiceSoap.ReverseTextAsync(Client2.ReverseService.ReverseTextRequest request) {
            return base.Channel.ReverseTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client2.ReverseService.ReverseTextResponse> ReverseTextAsync(string text) {
            Client2.ReverseService.ReverseTextRequest inValue = new Client2.ReverseService.ReverseTextRequest();
            inValue.Body = new Client2.ReverseService.ReverseTextRequestBody();
            inValue.Body.text = text;
            return ((Client2.ReverseService.ReviseServiceSoap)(this)).ReverseTextAsync(inValue);
        }
    }
}
